dmgbuild/core.py

Fix error when using Python 3: `TypeError: can only concatenate list (not "filter") to list`

Python 3 compatibility

---

.travis.yml

This will help ensure that the build doesn't break on older macOS
versions.

Downgrade tested Python version to 2.7

---

.travis.yml

Test only relevant system Python versions for macOS's since 10.7. This
helps to uncover any issues that are version-specific.

Test only relevant system Python versions for macOS's since 10.7

---

dmgbuild/core.py

Try `hdiutil detach` up to 5 times, with 1 second pause between retries.
Based on the [pull request](https://bitbucket.org/al45tair/dmgbuild/pull-requests/11) from @tomashanacek, the only difference is that it's not limited to return code 16.
Fixes #10

retry for hdiutil detach

---

doc/settings.rst
examples/settings.py

Add a note about pyobjc-framework-Quartz to the settings example and
documentation.

Note that badge icons require Quartz.

---

dmgbuild/licensing.py

Hello!
Currently, when we attempt to create a DMG using a RTF license provided as a **file path**, the resource that is created is a plain-text one rather than a RTF resource. The result is that the RTF underlying file data is printed verbatim in the final text-box rather than printed as rich text.
This behavior comes from [this condition](https://github.com/al45tair/dmgbuild/blob/master/dmgbuild/licensing.py#L434). In our RTF **file path** case, it will always be `false` because the type of `license_data` will always be `str` as [it is always opened in text mode](https://github.com/al45tair/dmgbuild/blob/master/dmgbuild/licensing.py#L431), and therefore the data will always be interpreted as plain-text rather than RTF.
This pull request aims to fix this by opening the file in **binary** …

Fix RTF license when input data is a file path

---

dmgbuild/core.py

In using dmgbuild (via [briefcase](https://github.com/beeware/briefcase)), the auto dmg size calculation has been consistently under calculating (by about 1.5%) on a large (~1.2GB) app bundle for me, leading to failed `hdiutil` command with 
```
File "briefcase/platforms/macOS/dmg.py", line 126, in package_app
self.dmgbuild.build_dmg(
File "dmgbuild/core.py", line 524, in build_dmg
os.symlink(target, name_in_image)
OSError: [Errno 28] No space left on device: '/Applications' -> '/Volumes/app_bundle/Applications'
```
I tracked it down to this line:
https://github.com/al45tair/dmgbuild/blob/fc1d8014e6c373c0fefc8fe023e73f805e10ead9/dmgbuild/core.py#L401
If all the calculations are done with base-10 instead of base-2 numbers, it works fine.  Perhaps related to [mac's move to base-10 sizing in …

change total_size calculation to base 10

---

dmgbuild/core.py

Default detach timeout may be not enough in some cases, like antivirus scanning of the new dmg, so its creation fails after force detach of the image. The ability to change the detach timeout/retry count should help in such cases.

Allow setting custom detach timeout

---

dmgbuild/core.py

First stab at a mechanism for providing feedback during the build_dmg operation.  
An extra parameter (callback) is provided to the build_dmg command which will be called by the build_dmg process as it progresses through its build.  The default implementation of the callback does nothing, so there is no change to the operation of the command.
If a user supplied callback is provided, then it receives a dictionary object which contains information about the operation currently being performed and includes any extra information that is available and relevant to that operation.

Added callback parameter to build_dmg

---

dmgbuild/core.py

Use `sync` to flush writes before attempting to detach, work around the following errors:
```
hdiutil: detach: timeout for DiskArbitration expired
hdiutil: detach: drive not detached
```
On a project that uses dmgbuild, no more timeouts since [switching to a version of dmgbuild containing this patch](https://github.com/openstenoproject/plover/pull/1266):
* before: the timeout error occurred on 44 of the 119 workflow runs (36.97%)
* after: no occurrence out of the 74 workflow runs

fix slowdowns when detaching

---

docs/settings.rst
setup.cfg
tests/test_samples.py

Pyobjc was removed as an explicit dependency; while the docs describe that dependency, we can provide a nicer UX for installing that extra requirement.
Fixes #50.

Add a definition for an badge_icons extra.

---

docs/settings.rst
src/dmgbuild/core.py

This adds (mostly documentation) support for creating ULMO (lzma compressed; macOS 10.15+ only) disk images, and for creating APFS disk images (macOS 10.13+ only).
For additional context, lzma can offer significantly reduced compression and is better than bzip2. I've also in some cases found extracting apps from APFS disk images to be more performant than HFS+ (up to 2x or by several seconds depending on the particular workload).

Add support for creating APFS and ULMO compressed disk images

---

docs/settings.rst

The package name is `dmgbuild`, not `dmv_build`.
Fixes #54.

Correct package name typo in documentation

---

.pre-commit-config.yaml
setup.cfg
src/dmgbuild/core.py

`setuptools.pkg_resources` has been a deprecated API for years; however, the 67.6.1 release has made this a *formal* deprecation, which raises warnings. 
This replaces the deprecated API with the officially supported API.
Includes pre-commit updates because the old config wasn't allowing commits.
Fixes #58

Replace setuptools pkg_resources with import lib

---

src/dmgbuild/licensing.py

As seen in the TypeScript based [dmg-license](https://github.com/argv-minus-one/dmg-license/blob/4268f2e822944fd670c1e197596396f233d6484e/src/Labels.ts#L284) implementation, the byte before the buttons should contain the length of the encoded string. Currently, it is hardcoded for the English buttons which is incorrect.

licensing: do not hardcode button length

---

README.rst
docs/index.rst

The README doesn't explicitly say that it's macOS specific tool.  It does now.
Fixes #63.

Add a README note about being macOS specific.

---

src/dmgbuild/__main__.py

Apple removed the 'python' executable a long time ago, so it's better to default to python3 instead.

Fix intepreter

---

pyproject.toml

Sphinx-autobuild 2024.2.4 deprecated support for Python 3.8. 
This PR adds in a version-conditional pin to allow docs to build on Python 3.8.

Correct sphinx-autobuild dependency for Py3.8

---

src/dmgbuild/__main__.py

Closes #128 
Adds new command line flag `--detach-retries`  which defaults to the current value of 5 and has a range of 1-30.

Add --detach-retries to command line. Closes #128

---

.github/workflows/ci.yml
.pre-commit-config.yaml
pyproject.toml
tox.ini

Python 3.8 is now EOL, so we can drop support.
Also removing macOS-12 from the CI matrix, as we're less than 2 months from the runner being removed.

Drop support for Python 3.8

---

.github/workflows/ci.yml
pyproject.toml
src/dmgbuild/core.py

Modifies the retry behavior when detaching disk images to (a) have more retries, and (b) use exponential backoff in the time between retries. 
Also ensures that stderr content is captured, rather than surfacing to the user. Any stderr content is included in the DMGError that is raised by the API.

Make detach behavior more resilient, and capture errors from hdiutil.

---

tests/examples/settings.py

Corrects the test example so that the language being used matches the button language, and the buttons are defined as strings (not bytes).
Fixes #199.

Correct the example to ensure custom buttons are read.

---

src/dmgbuild/core.py

If `hdiutil` is invoked in plist parsing mode, we need to ensure that stderr content isn't included in stdout, because that can cause parsing errors. Instead of piping `stderr` to `stdout`, leave stderr content as untouched so it will surface to the user.
Fixes #197.

Ensure that if hdiutil is producing parseable content, stderr isn't included.
